### ISSUE TITLE
Update User Information

### ISSUE THREAD

**Issue by hyecheol123** [hyecheol123/MakeBSSGreatAgain-API#12]
Admin and owner of the user can modify the user information
- [x] Ajv Input Validator
- [x] DB Query
- [x] Function (PUT: /user/{username})
- [x] Test Codes

**Comment by bsstayo** [comment]
[Email-Add]

If someone add Email, but already exist,
1) in his/her Email list
2) in another user's list
How can we handle these?

**Comment by bsstayo** [comment]
[Email-Add]

When someone wants to delete an Email, if it doesn't exist, throw an error?

**Comment by hyecheol123** [comment]
> [Email-Add]
> 
> If someone add Email, but already exist,
> 
> 1. in his/her Email list
> 2. in another user's list
>    How can we handle these?

1. For already existing username and email pairs, the change request will be ignored.
2. This is allowed.

**Comment by hyecheol123** [comment]
> [Email-Add]
> 
> When someone wants to delete an Email, if it doesn't exist, throw an error?

It is not an error. It just proceed but do not have any effects
