### ISSUE TITLE
Use nickname instead of nameEnglish / Add School(Company) and Major(Position) section

### ISSUE THREAD

**Issue by hyecheol123** [hyecheol123/MakeBSSGreatAgain-API#3]
**Use nickname instead of nameEnglish**
- [x] Change nameEnglish field to nickname (optional)
- [x] Change nameKorean field to legalName(legal_name)
- [x] Modify test codes

**Add School(Company) and Major(Position) section**
- [x] Avj validator
- [x] DB (Table + Queries)
- [x] Functions (Change POST /user)
- [x] Test Codes

**Comment by hyecheol123** [comment]
Add School(Company) and Major(Position) section

Not yet completed

**Comment by bsstayo** [comment]
Some simple questions

1. Do we need user's additional infos like address, phone number? OR we can update these later.
2. School(Company), Major(Position) is optional, right?

+) Will it be messy using <datalist> when input (2) infos - of course this is more related in front-end.

@hyecheol123

**Comment by hyecheol123** [comment]
@bsstayo 
1. Address will not be collected, but phone numbers are going to be collected (but they are not mandatory). As I will not allow other members to see other's phone number, this information will be located in a separated table for search efficiency.
2. School and Major information is optional, but as long as one field is provided, the other should also be provided. The information will be stored as nested object (JSON format)

**Comment by bsstayo** [comment]
@hyecheol123 

If someone double-majored, how can we handle this situation?
Maybe we can make a additional 'majorPosition' 😕 
Not only this case, but I'm afraid that there will be more corner case... 😨

**Comment by hyecheol123** [comment]
@bsstayo 
Just let them list up all majors they want to indicate
